import logging


logger = logging.getLogger(__name__)

CZO_DATA_CSV = "./data/czo.csv"

# a list of czo_ids to migrate. If empty or None, list to be generated by START_ROW_INDEX and END_ROW_INDEX
CZO_ID_LIST_TO_MIGRATE = []

# only work when CZO_ID_LIST_TO_MIGRATE is empty or NONE
START_ROW_INDEX = 0  # start row index in CZO_DATA_CSV
END_ROW_INDEX = 409  # end row index in CZO_DATA_CSV -- max 409


LOG_DIR = "./logs"
CLEAR_LOGS = False  # delete everything in the LOG_DIR

HS_URL = "localhost"  # dev-hs-6.cuahsi.org
PORT = "8000"  # https-443
USE_HTTPS = False
VERIFY_HTTPS = False  # check if HTTPS certificate is valid


CZO_ACCOUNTS = {
    "default": {"uname": "czo", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "national": {"uname": "czo_national", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "boulder": {"uname": "czo_boulder", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "eel": {"uname": "czo_eel", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "catalina-jemez": {"uname": "czo_catalina-jemez", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "reynolds": {"uname": "czo_reynolds", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "luquillo": {"uname": "czo_luquillo", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "sierra": {"uname": "czo_sierra", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "christina": {"uname": "czo_christina", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "shale hills": {"uname": "czo_shale-hills", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
    # "calhoun": {"uname": "czo_calhoun", "pwd": "123", "hs_url": HS_URL, "port": PORT, "use_https": USE_HTTPS, "verify_https": VERIFY_HTTPS},
}

BIG_FILE_SIZE_MB = 500

headers = {
    'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
}

USE_CACHED_FILES = True
CACHED_FILE_DIR = "/czo/2019-02-13_18-29-56"

MB_TO_BYTE = 1024 * 1024

README_FILENAME = "ReadMe.md"
README_COLUMN_MAP_PATH = './data/markdown_map.json'

# with open(README_COLUMN_MAP_PATH) as f:
#     README_COLUMN_MAP = json.load(f, object_pairs_hook=OrderedDict)

RUN_2ND_PASS = True

try:
    from local_settings import *
except ImportError:
    pass

