import logging

logger = logging.getLogger(__name__)

CZO_DATA_CSV = "./data/czo.csv"

# a list of czo_ids to migrate. If empty or None, list to be generated by START_ROW_INDEX and END_ROW_INDEX
CZO_ID_LIST_TO_MIGRATE = []

# only work when CZO_ID_LIST_TO_MIGRATE is empty or NONE
START_ROW_INDEX = 0  # start row index in CZO_DATA_CSV
END_ROW_INDEX = 399  # end row index in CZO_DATA_CSV -- max 399


LOG_DIR = "./logs"
CLEAR_LOGS = False  # delete everything in the LOG_DIR

HS_URL = "localhost"  # dev-hs-6.cuahsi.org

CZO_ACCOUNTS = {
    "default": {"uname": "czo", "pwd": "123", "hs_url": HS_URL},
    # "national": {"uname": "czo_national", "pwd": "123", "hs_url": HS_URL},
    # "boulder": {"uname": "czo_boulder", "pwd": "123", "hs_url": HS_URL},
    # "eel": {"uname": "czo_eel", "pwd": "123", "hs_url": HS_URL},
    # "catalina-jemez": {"uname": "czo_catalina-jemez", "pwd": "123", "hs_url": HS_URL},
    # "reynolds": {"uname": "czo_reynolds", "pwd": "123", "hs_url": HS_URL},
    # "luquillo": {"uname": "czo_luquillo", "pwd": "123", "hs_url": HS_URL},
}

BIG_FILE_SIZE_MB = 500

headers = {
    'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
}

USE_PREDOWNLOAD = False
PREDOWNLOAD_CSV = ""
if USE_PREDOWNLOAD:
    import pandas as pd
    predownload_df = pd.read_csv(PREDOWNLOAD_CSV,
                                 index_col="url_md5")
    PREDOWNLOAD_DICT = predownload_df.to_dict('index')

MB_TO_BYTE = 1024 * 1024

